# Generated by Django 3.1.5 on 2021-04-10 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_dvsusers'),
    ]

    operations = [
        migrations.AddField(
            model_name='dvsusers',
            name='test_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
