# Generated by Django 3.1.5 on 2021-04-10 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_dvsusers_test_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DVSusers',
        ),
    ]
